<div id="seeAuditBoarding" class="modal fade" tabindex="-1">
	<div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg">
		<div class="modal-content border-0">
			<div class="modal-header bg-primary text-white">
				<h3 class="modal-title w-100 text-center fst-normal">Auditoría SOP Boarding</h3>
				<button type="button" class="rounded-circle p-3 btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
	
			<div class="modal-body">
				<button type="button" id="printChart" class="btn btn-primary">Imprimir Gráfico</button>
				<div id="chart_div"></div>
			</div>

		</div>
	</div>
</div>