<div id="seeAuditBoarding" class="modal fade" tabindex="-1">
	<div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-xl">
		<div class="modal-content border-0">
			<div class="modal-header bg-success text-white">
				<h3 class="modal-title w-100 text-center fst-normal">Auditoría SOP Boarding</h3>
				<button type="button" class="rounded-circle p-3 btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>

			<div class="modal-body">
				<button type="button" id="printChart" class="btn btn-primary">Imprimir Gráfico</button>
				<div id="chart_div"></div>

				<table id="detalleAuditoria_final" class="table table-bordered table-hover table-striped table-sm display" cellpadding="0" width="100%">
					<thead class="sticky-top table-dark text-center align-middle">
						<tr>
							<th>Posición</th>
							<th># Punto</th>
							<th width="35%">Descripción</th>
							<th width="20%">Imagen</th>
							<th width="25%">Comentario</th>
							<th width="25%">Resultado</th>
						</tr>
					</thead>
					<tbody class="text-center align-middle">
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tbody>
				</table>
			</div>

		</div>
	</div>
</div>