<div class="position-fixed top-0 end-0 p-3" style="z-index: 1100">
  <div id="liveToast" class="toast border-0" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="toast-header border-0">
      <strong class="me-auto toast-title text-dark"></strong>
      <small class="toast-subtitle"></small>
      <button type="button" class="rounded-circle p-2 btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
    <div class="toast-body"></div>
  </div>
</div>